name: Develop

on:
  pull_request:
    branches:
      - 'develop*'

jobs:
  autoformatting:
    needs: pin_requirements
    uses: ./.github/workflows/autoformatting.yml
  testing:
    needs: autoformatting
    uses: ./.github/workflows/testing.yml
    secrets: inherit
